language: python
python:
  - "2.7.15"
  - "2.7"
install:
  - "pip install --upgrade setuptools"
  - "pip install flake8"
  - "pip install ."
script:
  - "flake8 --config .flake8 ."
  - "python setup.py test"
