language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install lxml
  - pip install ipaddr
  - pip install psutil
  - pip install sqlalchemy
  - pip install importlib
  - pip install yandextank
script: cd tests && nosetests

