core:
  type: dict
  allow_unknown: false
  schema:
    affinity:
      description: specify cpu core(s) to bind tank process to,  http://linuxhowtos.org/manpages/1/taskset.htm
      type: string
      default: ''
    api_jobno:
      description: tankapi job id, also used as test\'s directory name - determined by tank
      type: string
    artifacts_base_dir:
      description: base directory to store tests\' artifacts directories
      type: string
      default: ./logs
    artifacts_dir:
      description: directory inside base directory to store test\'s artifacts, defaults to api_jobno if null
      type: string
    cmdline:
      type: string
    exitcode:
      type: integer
    flush_config_to:
      description: path to store config
      type: string
    ignore_lock:
      description: if tank is locked ( *.lock file(s) presented in lock_dir), shoot nevertheless
      type: boolean
      default: false
    uuid:
      type: string
    pid:
      type: integer
    message:
      type: string
    lock_dir:
      description: directory to store *.lock files
      type: string
      default: /var/lock/
    operator:
      description: your username
      type: string
    taskset_path:
      type: string
      default: taskset
    debug:
      description: enable debug logging
      type: boolean
      default: false
    aggregator_max_wait:
      description: maximum data waiting time from aggregator
      type: integer
      default: 31
    skip_generator_check:
      description: enable tank running without load generator
      type: boolean
      default: false
version:
  type: string
